#define introduction 10
#define onlineregistration 770
#define quickstart 700
#define explorerandeditor 620
#define viewstyle 600
#define selections 400
#define usingthetoolbar 70
#define menureference 0
#define photomudreference 0
#define frmborder 1102
#define frmarteffects 15
#define artballs 0
#define artbricks 0
#define artclouds 0
#define artpencil 0
#define artplasma 0
#define artglass 0
#define artimpressionist 0
#define artlens 0
#define artpixelate 0
#define artpointillist 0
#define artpolar 0
#define artpuzzle 0
#define artreveffect 0
#define artripples 0
#define artsegment 0
#define artshadow 0
#define artskew 0
#define artswirl 0
#define artwarp 0
#define artocean 0
#define artwave 0
#define artwind 0
#define artzoomwave 0
#define autoenhance 440
#define frmblur 100
#define brightness 120
#define frmcalendar 0
#define frmcalendarevents 0
#define frmcoloradjust 0
#define frmcombine 150
#define frmconvert 570
#define frmcolorbatchadjust 630
#define frmhalftone 210
#define copyandpaste 50
#define filecopyfile 730
#define frmnew 260
#define crop 430
#define frmtoolbar 610
#define filedelete 410
#define drawingcolors 510
#define drawinglines 480
#define drawingtext 470
#define frmedgedetect 170
#define frmeditkeywords 750
#define frmsend 40
#define frmexpand 180
#define frmfileassoc 190
#define selectfiletypes 0
#define drawfillselection 500
#define drawfill 0
#define imageflip 420
#define frmfullscreen 60
#define grayscale 450
#define frmhisto 220
#define huesaturationandintensity 0
#define frmfilter 200
#define frmamp 90
#define frmlineoptions 240
#define colornegative 460
#define frmwebpage 550
#define frmmedian 250
#define frmcolormerge 780
#define fileopen 720
#define frmoptions 270
#define generaloptions 0
#define editingoptions 0
#define slideshowoptions 0
#define fileandcompressionoptions 0
#define exploreroptions 0
#define webpageoptions 0
#define panning 520
#define frmcomment 160
#define frminfo 230
#define photomosaic 290
#define frmsearch 790
#define frmprint 280
#define frmredeye 310
#define repeatlastoperation 640
#define frmresize 320
#define reverttolastsaved 710
#define frmrotate 330
#define frmsaveas 560
#define fileacquire 380
#define screencapture 130
#define frmdupsearch 690
#define editselectsimilarcolors 0
#define tagandselect 580
#define toolssetaswallpaper 540
#define frmsharpen 360
#define frmslideshow 660
#define frmspecialeffects 350
#define specaddrandomnoise 0
#define specemboss 0
#define specintensitydetect 0
#define specmosaic 0
#define specposterize 0
#define specsolarize 0
#define editstretchpaste 670
#define imagestretch 680
#define undoandredo 390
#define viewzoom 530
#define filetypes 70
#define jpgcompression 30
#define multipageimages 0
#define howto 650

